### ISSUE TITLE
Won't install ,help

### ISSUE THREAD

**Issue by DazSH** [SteveEdson/Octoprint-Blinkt#1]
Hi I'm excited to try your plugin and maybe attempt to adapt it to my needs (maybe dreaming) but my issue is it won't install at all.. Error msg on me everytime I try . Any ideas ?

**Comment by DazSH** [comment]
Collecting https://github.com/SteveEdson/Octoprint-Blinkt/find/master

```
ERROR: Cannot unpack file /tmp/pip-unpack-jH4f2R/master (downloaded from /tmp/pip-req-build-0qZjah, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-0qZjah
Downloading https://github.com/SteveEdson/Octoprint-Blinkt/find/master
Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
```

**Comment by SteveEdson** [comment]
Thanks for the interest, try installing it using this URL: https://github.com/SteveEdson/Octoprint-Blinkt/archive/master.zip and let me know how you get on.

**Comment by DazSH** [comment]
> 
> 
> Thanks for the interest, try installing it using this URL: https://github.com/SteveEdson/Octoprint-Blinkt/archive/master.zip and let me know how you get on.

Got it installed thanks ..
